"""movement fields

Revision ID: 2d3794f6e651
Revises: c003ce7f2e83
Create Date: 2025-12-18 22:03:40.786852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d3794f6e651'
down_revision: Union[str, Sequence[str], None] = 'c003ce7f2e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_movements_id'), 'movements', ['id'], unique=False)
    op.drop_constraint(op.f('movements_product_id_fkey'), 'movements', type_='foreignkey')
    op.create_foreign_key(None, 'movements', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_constraint(None, 'movements', type_='foreignkey')
    op.create_foreign_key(op.f('movements_product_id_fkey'), 'movements', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_movements_id'), table_name='movements')
    # ### end Alembic commands ###
